"""
print "   __________"
print "   |        |"
print "   |        |"
print "   |        O"
print "   |       /|\\"
print "   |       / \\"
print "   |"
print "   |"
print "___|_____"
"""
mystr_10 = "   __________\n   |        |\n   |        |\n   |        O\n   |       /|\\\n   |       / \\\n   |\n   |\n___|_____\n"
mystr_9  = "   __________\n   |        |\n   |        |\n   |        O\n   |       /|\\\n   |       / \n   |\n   |\n___|_____\n"
mystr_8  = "   __________\n   |        |\n   |        |\n   |        O\n   |       /|\\\n   |        \n   |\n   |\n___|_____\n"
mystr_7  = "   __________\n   |        |\n   |        |\n   |        O\n   |       /|\n   |        \n   |\n   |\n___|_____\n"
mystr_6  = "   __________\n   |        |\n   |        |\n   |        O\n   |        |\n   |        \n   |\n   |\n___|_____\n"
mystr_5  = "   __________\n   |        |\n   |        |\n   |        O\n   |        \n   |        \n   |\n   |\n___|_____\n"
mystr_4  = "   __________\n   |        |\n   |        |\n   |        \n   |        \n   |        \n   |\n   |\n___|_____\n"
mystr_3  = "   __________\n   |        \n   |        \n   |        \n   |        \n   |        \n   |\n   |\n___|_____\n"
mystr_2  = "   \n   |        \n   |        \n   |        \n   |        \n   |        \n   |\n   |\n___|_____\n"
mystr_1  = "   \n           \n           \n           \n           \n           \n   \n   \n_________\n"
mystr_0  = "   \n           \n           \n           \n           \n           \n   \n   \n\n"

images_steps = [mystr_0, mystr_1, mystr_2, mystr_3, mystr_4, mystr_5, mystr_6, mystr_7, mystr_8, mystr_9, mystr_10]
